### ISSUE TITLE
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[InjectionToken IUrlConstantService injection token

### ISSUE THREAD

**Issue by kbmanikanta** [8Tesla8/angular-oidc#2]
core.js:6210 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[InjectionToken IUrlConstantService injection token -> InjectionToken IUrlConstantService injection token -> InjectionToken IUrlConstantService injection token]: 
  NullInjectorError: No provider for InjectionToken IUrlConstantService injection token!
NullInjectorError: R3InjectorError(AppModule)[InjectionToken IUrlConstantService injection token -> InjectionToken IUrlConstantService injection token -> InjectionToken IUrlConstantService injection token]: 
  NullInjectorError: No provider for InjectionToken IUrlConstantService injection token!
    at NullInjector.get (vendor.js:29508:27)
    at R3Injector.get (vendor.js:29675:33)
    at R3Injector.get (vendor.js:29675:33)
    at R3Injector.get (vendor.js:29675:33)
    at NgModuleRef$1.get (vendor.js:43705:33)
    at Object.get (vendor.js:43419:35)
    at lookupTokenUsingModuleInjector (vendor.js:21795:39)
    at getOrCreateInjectable (vendor.js:21907:12)
    at Module.ɵɵdirectiveInject (vendor.js:33099:12)
    at NodeInjectorFactory.LogoutCallbackComponent_Factory [as factory] (main.js:407:183)
    at resolvePromise (polyfills.js:10606:31)
    at resolvePromise (polyfills.js:10560:17)
    at polyfills.js:10672:17
    at ZoneDelegate.invokeTask (polyfills.js:9799:31)
    at Object.onInvokeTask (vendor.js:46946:33)
    at ZoneDelegate.invokeTask (polyfills.js:9798:60)
    at Zone.runTask (polyfills.js:9571:47)
    at drainMicroTaskQueue (polyfills.js:9975:35)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:9884:

![image](https://user-images.githubusercontent.com/5341848/188000276-ce00e960-47e1-47da-8a1f-82fb68a37842.png)

Can anyone help me how to fix this?

**Comment by 8Tesla8** [comment]
You need to make the implementation of service 
export interface IAuthUrlConstantService {
    getServiceName(): string;
    getAuthSuccessCallbackRedirectUrl(): string;
    getLogoutCallBackRedirectUrl(): string;
}

After that put this service in appmodule

 providers: [
    { provide: AuthUrlConstantServiceToken, useClass: YourClassName }
  ],
